# Routinify Backend RuboCop設定
# Rails 8.0 + API専用アプリケーション向けの設定

require:
  - rubocop-rails-omakase

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/factories/**/*'
    - 'spec/support/**/*'

# レイアウト関連
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundMethodBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/IndentationWidth:
  Width: 2

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# スタイル関連
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/IfUnlessModifier:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/UnlessElse:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/DefWithParentheses:
  EnforcedStyle: require_parentheses

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Proc:
  EnforcedStyle: lambda

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%x': '()'
    '%s': '()'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyElse:
  EnforcedStyle: empty

Style/GuardClause:
  MinBodyLength: 1

Style/IdenticalConditionalBranches:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NestedModifier:
  Enabled: false

Style/Next:
  Enabled: true

Style/RedundantReturn:
  EnforcedStyle: multiple_return_values

Style/RedundantSelf:
  EnforcedStyle: allow_self

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: true

Style/Semicolon:
  EnforcedStyle: semicolon

Style/SingleLineBlockParams:
  EnforcedStyle: braces

Style/SpaceAfterColon:
  EnforcedStyle: space

Style/SpaceAfterComma:
  EnforcedStyle: space

Style/SpaceAfterMethodName:
  EnforcedStyle: space

Style/SpaceAfterNot:
  EnforcedStyle: space

Style/SpaceAfterSemicolon:
  EnforcedStyle: space

Style/SpaceAroundBlockParameters:
  EnforcedStyle: space

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Style/SpaceAroundKeyword:
  EnforcedStyle: space

Style/SpaceAroundOperators:
  EnforcedStyle: space

Style/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Style/SpaceBeforeComma:
  EnforcedStyle: no_space

Style/SpaceBeforeComment:
  EnforcedStyle: space

Style/SpaceBeforeSemicolon:
  EnforcedStyle: no_space

Style/SpaceInHashLiteral:
  EnforcedStyle: space

Style/SpaceInParens:
  EnforcedStyle: no_space

Style/SpaceInRangeLiteral:
  EnforcedStyle: space

Style/SpaceInsideArrayPercentLiteral:
  EnforcedStyle: space

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/SpaceInsideParens:
  EnforcedStyle: no_space

Style/SpaceInsidePercentLiteralDelimiters:
  EnforcedStyle: space

Style/SpaceInsideRangeLiteral:
  EnforcedStyle: space

Style/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/Tab:
  EnforcedStyle: spaces

Style/TrailingBlankLines:
  EnforcedStyle: final_newline

Style/TrailingWhitespace:
  EnforcedStyle: final_newline

Style/TrivialAccessors:
  AllowPredicates: true
  AllowDSLWriters: true
  ExactNameMatch: true

Style/UnneededCapitalW:
  EnforcedStyle: lowercase

Style/UnneededInterpolation:
  EnforcedStyle: all

Style/UnneededPercentQ:
  EnforcedStyle: percent_q

Style/VariableInterpolation:
  EnforcedStyle: braces

Style/WhenThen:
  EnforcedStyle: case

Style/WhileUntilDo:
  EnforcedStyle: do

Style/YodaCondition:
  EnforcedStyle: always

# メトリクス関連
Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 8

# 命名関連
Naming/AccessorMethodName:
  EnforcedStyle: snake_case

Naming/AsciiIdentifiers:
  EnforcedStyle: ascii

Naming/BinaryOperatorParameterName:
  EnforcedStyle: left_and_right

Naming/BlockParameterName:
  EnforcedStyle: snake_case

Naming/ClassAndModuleCamelCase:
  EnforcedStyle: camelCase

Naming/ConstantName:
  EnforcedStyle: SCREAMING_SNAKE_CASE

Naming/FileName:
  EnforcedStyle: snake_case

Naming/HeredocDelimiterCase:
  EnforcedStyle: uppercase

Naming/HeredocDelimiterNaming:
  EnforcedStyle: descriptive

Naming/MemoizedInstanceVariableName:
  EnforcedStyle: snake_case

Naming/MethodName:
  EnforcedStyle: snake_case

Naming/MethodParameterName:
  EnforcedStyle: snake_case

Naming/PredicateName:
  EnforcedStyle: snake_case
  ForbiddenPrefixes:
    - is_
    - are_
    - was_
    - were_
    - will_
    - should_
    - has_
    - have_
    - had_
    - can_
    - could_
    - may_
    - might_
    - must_
    - shall_

Naming/RescuedExceptionsVariableName:
  EnforcedStyle: snake_case

Naming/UncommunicativeMethodParameterName:
  EnforcedStyle: snake_case

Naming/UncommunicativeParameterName:
  EnforcedStyle: snake_case

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/VariableNumber:
  EnforcedStyle: snake_case

# セキュリティ関連
Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/Eval:
  Enabled: true

Security/Unsafe:
  Enabled: true

# Rails関連
Rails/ApplicationController:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationMailer:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/ContentTag:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/EnvironmentComparison:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/IgnoredColumnsAssignment:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/LinkToBlank:
  Enabled: true

Rails/LinkToHasBlankHref:
  Enabled: true

Rails/LinkToParams:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Rails/MigrationCombinator:
  Enabled: true

Rails/MigrationTimestamps:
  Enabled: true

Rails/MissingForeignKey:
  Enabled: true

Rails/MissingPresenceValidation:
  Enabled: true

Rails/MissingValidation:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantPresenceValidationOnHasOne:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/RefuteMethods:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/RequireDependency:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SafeNavigationWithBlank:
  Enabled: true

Rails/SafeNavigationWithPresent:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/SquishedStringHeredoc:
  Enabled: true

Rails/StripHeredoc:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/UnknownEnv:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/ValidationWithMessage:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/WhereOr:
  Enabled: true

Rails/YAML:
  Enabled: true

# パフォーマンス関連
Performance/ArraySemiInfiniteRangeCheck:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BindCall:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MapMethodChain:
  Enabled: true

Performance/NewArrayWithHashArgument:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantSort:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UnneededSort:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MapMethodChain:
  Enabled: true

Performance/NewArrayWithHashArgument:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantSort:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UnneededSort:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

# レガシー関連
Lint/AmbiguousBlockAssociation:
  EnforcedStyle: explicit

Lint/AmbiguousOperator:
  EnforcedStyle: explicit

Lint/AmbiguousRegexpLiteral:
  EnforcedStyle: explicit

Lint/AssignmentInCondition:
  EnforcedStyle: assign_to_condition

Lint/BlockAlignment:
  EnforcedStyle: start_of_block

Lint/ConditionalAssignment:
  EnforcedStyle: assign_to_condition

Lint/DeprecatedClassMethods:
  EnforcedStyle: explicit

Lint/DeprecatedConstants:
  EnforcedStyle: explicit

Lint/DeprecatedOpenSSL:
  EnforcedStyle: explicit

Lint/DuplicateCaseCondition:
  EnforcedStyle: explicit

Lint/DuplicateHashKey:
  EnforcedStyle: explicit

Lint/DuplicateMethods:
  EnforcedStyle: explicit

Lint/DuplicateRequire:
  EnforcedStyle: explicit

Lint/DuplicateRescueException:
  EnforcedStyle: explicit

Lint/EachWithObjectArgument:
  EnforcedStyle: explicit

Lint/ElseLayout:
  EnforcedStyle: same_line

Lint/EmptyBlock:
  EnforcedStyle: empty

Lint/EmptyClass:
  EnforcedStyle: explicit

Lint/EmptyConditionalBody:
  EnforcedStyle: empty

Lint/EmptyEnsure:
  EnforcedStyle: empty

Lint/EmptyExpression:
  EnforcedStyle: empty

Lint/EmptyFile:
  EnforcedStyle: empty

Lint/EmptyInterpolation:
  EnforcedStyle: empty

Lint/EmptyWhen:
  EnforcedStyle: empty

Lint/EndAlignment:
  EnforcedStyle: variable

Lint/EndInMethod:
  EnforcedStyle: explicit

Lint/EnsureReturn:
  EnforcedStyle: explicit

Lint/ErbNewArguments:
  EnforcedStyle: explicit

Lint/FlipFlop:
  EnforcedStyle: explicit

Lint/FloatOutOfRange:
  EnforcedStyle: explicit

Lint/FormatParameterMismatch:
  EnforcedStyle: explicit

Lint/FormatStringMismatch:
  EnforcedStyle: explicit

Lint/FormatStringToken:
  EnforcedStyle: explicit

Lint/GlobalVars:
  EnforcedStyle: explicit

Lint/HashCompareByIdentity:
  EnforcedStyle: explicit

Lint/ImplicitStringConcatenation:
  EnforcedStyle: explicit

Lint/InheritException:
  EnforcedStyle: explicit

Lint/InterpolationCheck:
  EnforcedStyle: explicit

Lint/Iri:
  EnforcedStyle: explicit

Lint/IrregularWhitespace:
  EnforcedStyle: explicit

Lint/ItWithoutBlock:
  EnforcedStyle: explicit

Lint/LambdaWithoutLiteralBlock:
  EnforcedStyle: explicit

Lint/LiteralAsCondition:
  EnforcedStyle: explicit

Lint/LiteralInInterpolation:
  EnforcedStyle: explicit

Lint/Loop:
  EnforcedStyle: explicit

Lint/MissingCopEnableDirective:
  EnforcedStyle: explicit

Lint/MissingSuper:
  EnforcedStyle: explicit

Lint/MixedRegexpCaptureTypes:
  EnforcedStyle: explicit

Lint/MultipleComparison:
  EnforcedStyle: explicit

Lint/NestedMethodDefinition:
  EnforcedStyle: explicit

Lint/NextWithoutAccumulator:
  EnforcedStyle: explicit

Lint/NonDeterministicRequireOrder:
  EnforcedStyle: explicit

Lint/NonLocalExitFromIterator:
  EnforcedStyle: explicit

Lint/NumberConversion:
  EnforcedStyle: explicit

Lint/NumberInInterpolation:
  EnforcedStyle: explicit

Lint/OrderedMagicComments:
  EnforcedStyle: explicit

Lint/OutOfRangeRegexpRef:
  EnforcedStyle: explicit

Lint/OverwrittenArgument:
  EnforcedStyle: explicit

Lint/ParenthesesAsGroupedExpression:
  EnforcedStyle: explicit

Lint/PercentStringArray:
  EnforcedStyle: explicit

Lint/PercentSymbolArray:
  EnforcedStyle: explicit

Lint/RaiseException:
  EnforcedStyle: explicit

Lint/RandOne:
  EnforcedStyle: explicit

Lint/RedundantWithIndex:
  EnforcedStyle: explicit

Lint/RedundantWithObject:
  EnforcedStyle: explicit

Lint/RedundantRequireStatement:
  EnforcedStyle: explicit

Lint/RedundantSplatExpansion:
  EnforcedStyle: explicit

Lint/RedundantStringCoercion:
  EnforcedStyle: explicit

Lint/RedundantWithObject:
  EnforcedStyle: explicit

Lint/RequireParentheses:
  EnforcedStyle: explicit

Lint/RescueType:
  EnforcedStyle: explicit

Lint/SafeNavigationChain:
  EnforcedStyle: explicit

Lint/SafeNavigationConsistency:
  EnforcedStyle: explicit

Lint/SafeNavigationWithBlank:
  EnforcedStyle: explicit

Lint/SafeNavigationWithPresent:
  EnforcedStyle: explicit

Lint/ScriptPermission:
  EnforcedStyle: explicit

Lint/SelfAssignment:
  EnforcedStyle: explicit

Lint/ShadowedArgument:
  EnforcedStyle: explicit

Lint/ShadowedException:
  EnforcedStyle: explicit

Lint/ShadowingOuterLocalVariable:
  EnforcedStyle: explicit

Lint/StructNewOverride:
  EnforcedStyle: explicit

Lint/SuppressedException:
  EnforcedStyle: explicit

Lint/Syntax:
  EnforcedStyle: explicit

Lint/ToEnumArguments:
  EnforcedStyle: explicit

Lint/ToJSON:
  EnforcedStyle: explicit

Lint/TopLevelReturnWithArgument:
  EnforcedStyle: explicit

Lint/TrailingCommaInAttributeDeclaration:
  EnforcedStyle: explicit

Lint/UnderscorePrefixedVariableName:
  EnforcedStyle: explicit

Lint/UnifiedInteger:
  EnforcedStyle: explicit

Lint/UnneededCondition:
  EnforcedStyle: explicit

Lint/UnneededDisable:
  EnforcedStyle: explicit

Lint/UnneededSplatExpansion:
  EnforcedStyle: explicit

Lint/UnreachableCode:
  EnforcedStyle: explicit

Lint/UnreachableLoop:
  EnforcedStyle: explicit

Lint/UnusedBlockArgument:
  EnforcedStyle: explicit

Lint/UnusedMethodArgument:
  EnforcedStyle: explicit

Lint/UnusedVariable:
  EnforcedStyle: explicit

Lint/UriEscapeUnescape:
  EnforcedStyle: explicit

Lint/UriRegexp:
  EnforcedStyle: explicit

Lint/UselessAssignment:
  EnforcedStyle: explicit

Lint/UselessAccessModifier:
  EnforcedStyle: explicit

Lint/UselessComparison:
  EnforcedStyle: explicit

Lint/UselessElseWithoutRescue:
  EnforcedStyle: explicit

Lint/UselessSetterCall:
  EnforcedStyle: explicit

Lint/Void:
  EnforcedStyle: explicit

Lint/VoidReturn:
  EnforcedStyle: explicit

Lint/YodaCondition:
  EnforcedStyle: explicit