# Routinify Backend RuboCop設定
# Rails 8.0 + API専用アプリケーション向けの設定

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

# 基本的なスタイル設定
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# メトリクス
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

# レイアウト
Layout/EmptyLinesAroundMethodBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

# 命名規則
Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/AccessorMethodName:
  AllowedNames:
    - 'id'
    - 'to_s'
    - 'to_i'
    - 'to_a'
    - 'to_h'

# その他
Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WordArray:
  MinSize: 3

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'
    '%r': '()'
    '%x': '()'
    '%s': '()'
    '%q': '()'
    '%Q': '()'