name: PR Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start services
      run: |
        docker compose -f docker-compose.test.yml build --no-cache backend
        docker compose -f docker-compose.test.yml up -d db
        docker compose -f docker-compose.test.yml up -d backend

    - name: Wait for services to be ready
      run: |
        docker compose -f docker-compose.test.yml exec -T db pg_isready -U postgres
        sleep 10

    - name: Setup database with ridgepole
      env:
        DATABASE_HOST: db
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: password
        RAILS_ENV: test
      run: |
        docker compose -f docker-compose.test.yml exec -T backend bundle exec rails db:create
        echo "Database created successfully"
        docker compose -f docker-compose.test.yml exec -T backend bundle exec ridgepole --config ./config/database.yml --file ./db/Schemafile --env test --apply
        echo "Ridgepole applied successfully"
        docker compose -f docker-compose.test.yml exec -T backend bundle exec rails db:schema:dump
        echo "Schema dumped successfully"
        docker compose -f docker-compose.test.yml exec -T backend bundle exec rails runner "puts ActiveRecord::Base.connection.tables"
        echo "Database tables listed above"

    - name: Run RSpec tests
      env:
        DATABASE_HOST: db
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: password
        RAILS_ENV: test
      run: docker compose -f docker-compose.test.yml exec -T backend bundle exec rspec --format documentation

    - name: Run RuboCop (check)
      run: docker compose -f docker-compose.test.yml exec -T backend bundle exec rubocop --format progress --format offenses --out rubocop.txt

    - name: Run RuboCop (auto-correct)
      run: docker compose -f docker-compose.test.yml exec -T backend bundle exec rubocop --auto-correct --format progress

    - name: Run Brakeman security check
      run: docker compose -f docker-compose.test.yml exec -T backend bundle exec brakeman --no-progress --format json --output brakeman-report.json

    - name: Copy test results from container
      run: |
        docker compose -f docker-compose.test.yml cp backend:/app/rubocop.txt ./backend/rubocop.txt
        docker compose -f docker-compose.test.yml cp backend:/app/brakeman-report.json ./backend/brakeman-report.json

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend-test-results
        path: |
          backend/rubocop.txt
          backend/brakeman-report.json
        retention-days: 7

    - name: Stop services
      if: always()
      run: docker compose -f docker-compose.test.yml down

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend service
      run: docker compose -f docker-compose.test.yml build frontend

    - name: Run tests
      run: docker compose -f docker-compose.test.yml run --rm frontend pnpm test:run

    - name: Run type check
      run: docker compose -f docker-compose.test.yml run --rm frontend pnpm tsc --noEmit

    - name: Run Prettier (check)
      run: docker compose -f docker-compose.test.yml run --rm frontend pnpm format:check

    - name: Run Prettier (auto-fix)
      run: docker compose -f docker-compose.test.yml run --rm frontend pnpm format

    - name: Copy test results from container
      run: |
        docker compose -f docker-compose.test.yml run --rm frontend pnpm test:run --reporter=json --outputFile=test-results.json || true
        docker compose -f docker-compose.test.yml cp frontend:/app/test-results.json ./frontend/test-results.json || true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-test-results
        path: |
          frontend/test-results.json
          frontend/test-results/
        retention-days: 7

  test-results:
    name: Test Results Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download backend test results
      uses: actions/download-artifact@v4
      with:
        name: backend-test-results
        path: backend-results

    - name: Download frontend test results
      uses: actions/download-artifact@v4
      with:
        name: frontend-test-results
        path: frontend-results

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          frontend-results/test-results/
        comment_mode: create
        compare_to_earlier_commit: true 